version: "3"

services:
  bot:
    build:
          context: .
          dockerfile: Dockerfile
    container_name: discord_bot
    volumes:
            - /home/soybean44/code/python/Discord-Bot:/app
    restart: always
    ports:
      - "6463:6472"
