name: Deploy Bot
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Twingate
        uses: twingate/github-action@v1
        with:
          service-key: ${{ secrets.SERVICE_KEY }}

      - name: executing remote ssh commands using ssh key
        run: |
          mkdir ~/.ssh
          cat '${{ secrets.KEY }}' > ~/.ssh/id_rsa.pub
          ssh ${{ secrets.USERNAME }}@${{secrets.HOST}}
          whoami
